name: Upload Python Package

on:
  push:
    branches: [ main ]
    paths:
      - "version"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  Publisher:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish packages
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        password: ${{ secrets.PIPY_API_TOKEN }}